<a href="https://colab.research.google.com/github/ranjit051098/lets-upgrade/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Question1
import numpy as np
arr=np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [12]:
#question2
l1=[]
l2=[]
for i in range(0,5):
  n=int(input())
  l1.append(n)
for i in range(0,5):
  m=int(input())
  l2.append(m)  
print(l1)
print(l2)

arr1=np.asarray(l1)
arr2=np.asarray(l2)
arr3=np.concatenate((arr1,arr2))
print(arr3)

print(np.sort(arr3))

12
10
20
58
98
65
32
87
41
16
[12, 10, 20, 58, 98]
[65, 32, 87, 41, 16]
[12 10 20 58 98 65 32 87 41 16]
[10 12 16 20 32 41 58 65 87 98]


In [15]:
#Question3
arr=np.array([[1,2,3],[5,8,9]])
print(arr.ndim)
arr.size

2


6

In [16]:
#Question4
arr=np.array([1,2,3,4])
print(np.reshape(arr,(-1,2)))

[[1 2]
 [3 4]]


In [20]:
#Question5
arr1=np.array([[1,2,3],[8,9,71]])
arr2=np.array([[4,5,6],[5,4,3]])
arr3=np.hstack((arr1,arr2))
print(arr3)
arr4=np.vstack((arr1,arr2))
print(arr4)

[[ 1  2  3  4  5  6]
 [ 8  9 71  5  4  3]]
[[ 1  2  3]
 [ 8  9 71]
 [ 4  5  6]
 [ 5  4  3]]


In [ ]:
#Question6
using unique() function we can get unique items and count of unique items